---
name: Create Github Tag
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update_tag.sh -m $(git log -1 --pretty=%B)
