---
name: Create Github Tag
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          commit_message: ${{ github.event.head_commit.message }}

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update_tag.sh -m $commit_message
